# Generated by Django 2.1.7 on 2019-03-31 14:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ngo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityHomeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charityHomeType', ngo.models.LowerCaseCharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', ngo.models.LowerCaseCharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=ngo.models.user_directory_path_images)),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('unverified', 'unverified'), ('verified', 'verified'), ('satisfied', 'satisfied'), ('rejected', 'rejected'), ('deleted', 'deleted')], default='unverified', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Needs',
            },
        ),
        migrations.CreateModel(
            name='NgoDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ngo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mapLocation', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=2)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('contactNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('amountRaised', models.IntegerField(default=0)),
                ('taxCertificate', models.FileField(blank=True, null=True, upload_to=ngo.models.user_directory_path_certificate)),
                ('charityHomeType', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngo.CharityHomeType')),
                ('city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngo.City')),
            ],
        ),
        migrations.AddField(
            model_name='needs',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='ngo.NgoDetail'),
        ),
        migrations.AddField(
            model_name='images',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ngo.NgoDetail'),
        ),
        migrations.CreateModel(
            name='NgoImage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ngo.ngodetail',),
        ),
    ]
